# SwifterLog document generator jazzy settings

copyright: Copyright 2016-2019 rien@balancingrock.nl
author: Balancingrock
module: SwifterLog
hide_documentation_coverage: true
xcodebuild_arguments: [-target, SwifterLog]
github_url: https://github.com/Balancingrock/SwifterLog
output: ~/Documents/Websites/swiftfire.nl/projects/swifterlog/reference
clean: true
theme: fullwidth
readme: README.md
documentation: docs/*.md
